# -*- coding: utf-8 -*-
"""yolov8_seg_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vWmTpq6dyXa20j5xAcXeu9BRMnOA3GW_
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

!pip install ultralytics

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="----your API key----")
project = rf.workspace("diplom-qz7q6").project("defects-2q87r")
version = project.version(16)
dataset = version.download("yolov8")

!mkdir datasets
!cp -rf Defects-16/* datasets/
!yolo segment train data=datasets/data.yaml model=yolov8m-seg.pt epochs=8 imgsz=[640,480] batch=-1

from google.colab import files
files.download('runs/segment/train8/weights/best.pt')
